# Generated by Django 5.2.6 on 2025-09-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_id_teacher_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='no',
            new_name='id',
        ),
    ]
