# Generated by Django 5.2.6 on 2025-09-14 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='create_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('Author_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='blog/images')),
                ('Category', models.CharField(choices=[('web development', 'Web Development'), ('programming', 'Programming'), ('technology', 'Technology'), ('news', 'News'), ('entertainment', 'Entertainment'), ('sports', 'Sports'), ('travel', 'Travel'), ('lifestyle', 'Lifestyle'), ('javascripts', 'JavaScript')], max_length=100)),
            ],
        ),
    ]
