# Generated by Django 5.2.6 on 2025-09-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stuff',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
